# Generated by Django 4.2.2 on 2023-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='efficiency',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
