# Generated by Django 4.2.2 on 2023-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='efficiency',
            field=models.IntegerField(default=0),
        ),
    ]
